#!/usr/bin/env ruby -S rake --verbose --trace --rakefile
# -*- encoding: utf-8 -*-

def env_default(name, fallback=nil)
  value = ENV[name.to_s]
  return value.strip if value and not value.to_s.empty?

  if block_given?
    value = yield
    return value.strip if value and not value.to_s.empty?
  end

  fallback
end

$configuration = env_default(:CONFIGURATION, 'Release')

task :default => "build"

desc "build"
task :build => ["build:growlmail"] do
  puts "Done building"
end

desc "package"
task :package => ["package:growlmail"] do
end

namespace "package" do
  desc "package growlmail"
  task :growlmail => ["build:growlmail"] do
	system "cd GrowlMail && xcodebuild -configuration $configuration -workspace GrowlMail.xcworkspace -scheme \"Package GrowlMail\" build"
  end
end

namespace "build" do
  desc "build growlmail"
  task :growlmail do
  	system "cd GrowlMail && xcodebuild -configuration $configuration build"
  end
end
